/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TODOApp;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        CommandManager commandManager;
        DataService dataService;
        String fileFormatCmd = "";

        System.out.print("file Choose the save format (1): CSV, (2): DB, default is CSV : ");
        fileFormatCmd = scanner.nextLine();

        if (fileFormatCmd.equals("2")) {
            dataService = new DBConnectionManager();
        } else {
            dataService = new CSVFileManager();
        }

        commandManager = new CommandManager(dataService);
        commandManager.inputCommand();

        System.out.println("Program Down");
        scanner.close();
    }
}